// Code generated by ntaps. DO NOT EDIT.
package di

import (
	"github.com/geb/aweproj/ses3/shared"
	"github.com/pkg/errors"

	"github.com/labstack/echo/v4"
)

func NewEcho(validator shared.Validator) (*echo.Echo, error) {
	e := echo.New()
	e.Validator = validator
	return e, nil
}

func init() {
	if err := Container.Provide(NewEcho); err != nil {
		panic(errors.Wrap(err, "failed to provide echo"))
	}
}
