// Code generated by ntaps. DO NOT EDIT.
package inventory

import (
	"github.com/geb/aweproj/book-store/interfaces"
	"github.com/geb/aweproj/book-store/shared"
)

type (
	Controller struct {
		SharedHolder     shared.Holder
		InterfacesHolder interfaces.Holder
	}
)

func NewController(sh shared.Holder, ih interfaces.Holder) (*Controller, error) {
	return &Controller{sh, ih}, nil
}
