// Code generated by ntaps. DO NOT EDIT.
package healthcheck

import (
	"github.com/geb/aweproj/ses3/shared"

	"context"
	healthcheck_dto "github.com/geb/aweproj/ses3/shared/dto/healthcheck"
	// - healthcheck-import-end
)

type (
	Service interface {

		// - healthcheck-check-start
		Check(ctx context.Context, request healthcheck_dto.CheckRequestDto) (*healthcheck_dto.CheckResponseDto, error)
		// - healthcheck-check-end

		// - healthcheck-service-end
	}

	service struct {
		SharedHolder shared.Holder

		// - healthcheck-service-implementation-end
	}
)

func NewService(holder shared.Holder) (Service, error) {
	return &service{holder}, nil
}
