// Code generated by ntaps. DO NOT EDIT.
package healthcheck

import (
	"context"
	healthcheck_dto "github.com/geb/aweproj/book-store/shared/dto/healthcheck"

	"github.com/geb/aweproj/book-store/application"
	"github.com/geb/aweproj/book-store/shared"
	// - healthcheck-import-end
)

type (
	ViewService interface {

		// - healthcheck-check-start
		Check(ctx context.Context, request healthcheck_dto.CheckRequestDto) (*healthcheck_dto.CheckResponseDto, error)
		// - healthcheck-check-end

		// - healthcheck-view-service-end
	}

	service struct {
		SharedHolder      shared.Holder
		ApplicationHolder application.Holder
	}
)

func NewViewService(sh shared.Holder, ah application.Holder) (ViewService, error) {
	return &service{sh, ah}, nil
}
