version: '3'

networks:
  search-network:
    driver: bridge

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - search-network

  mysql:
    image: mysql
    ports:
      - 3306:3306
    networks:
      - search-network

