// Code generated by ntaps. DO NOT EDIT.
package application

import (
	"github.com/geb/aweproj/ses3/application/shopping"
	"go.uber.org/dig"

	"github.com/geb/aweproj/ses3/application/healthcheck"

)

type (
	Holder struct {
		dig.In

		// - healthcheck-domain-start
		HealthCheckService healthcheck.Service
		// - healthcheck-domain-end

		// - shopping-domain-start
		Shopping shopping.Service
		// - shopping-domain-end
		
		// - application-holder-end
	}
)
