// Code generated by ntaps. DO NOT EDIT.
package interfaces

import (
	"github.com/geb/aweproj/ses3/interfaces/shopping"
	"github.com/pkg/errors"

	"github.com/geb/aweproj/ses3/interfaces/healthcheck"

	"go.uber.org/dig"
)

func Register(container *dig.Container) error {

	// - healthcheck-view-service-start
	if err := container.Provide(healthcheck.NewViewService); err != nil {
		return errors.Wrap(err, "failed to provide healthcheck app service")
	}
	// - healthcheck-view-service-end

	// - shopping-domain-start
	if err := container.Provide(shopping.NewViewService); err != nil {
		return errors.Wrap(err, "failed to provide healthcheck app service")
	}
	// - shopping-domain-end

	return nil
}
