// Code generated by ntaps. DO NOT EDIT.
package interfaces

import (
	"go.uber.org/dig"

	"github.com/geb/aweproj/ses3/interfaces/healthcheck"

)

type (
	Holder struct {
		dig.In


		// - Healthcheck-view-service-start
		HealthcheckViewService healthcheck.ViewService
		// - Healthcheck-view-service-end

		// interfaces-view-service-end
	}
)
