// Code generated by ntaps. DO NOT EDIT.
package interfaces

import (
	"github.com/geb/aweproj/ses3/interfaces/inventory"
	"go.uber.org/dig"

	"github.com/geb/aweproj/ses3/interfaces/healthcheck"
)

type (
	Holder struct {
		dig.In

		// - Healthcheck-view-service-start
		HealthCheckViewService healthcheck.ViewService
		// - Healthcheck-view-service-end

		// - Inventory-view-service-start
		InventoryViewService inventory.ViewService
		// - Inventory-view-service-end

		// interfaces-view-service-end
	}
)
