basePath: '{{.BasePath}}'
definitions:
  dto.MandatoryRequestV2Dto:
    properties:
      Accept-Language:
        type: string
      X-Username:
        type: string
    required:
    - Accept-Language
    - X-Username
    type: object
  healthcheck.CheckResponseDto:
    type: object
  shopping.BookBulkReq:
    properties:
      books:
        items:
          $ref: '#/definitions/shopping.CreateBookReq'
        type: array
    type: object
  shopping.BookDto:
    properties:
      author:
        type: string
      id:
        type: integer
      publisher:
        $ref: '#/definitions/shopping.PublisherDto'
        type: object
      title:
        type: string
    type: object
  shopping.CreateBookReq:
    properties:
      author:
        type: string
      pubId:
        type: integer
      title:
        type: string
    type: object
  shopping.PublisherDto:
    properties:
      countryId:
        type: integer
      id:
        type: integer
      name:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /application/health:
    get:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - default: guest
        description: guest
        in: header
        name: X-Username
        required: true
        type: string
      - default: EN
        description: EN
        in: header
        name: Accept-Language
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthcheck.CheckResponseDto'
            type: object
      summary: Healthcheck
      tags:
      - healthcheck-controller
  /shopping/book/bulk/create:
    post:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - default: guest
        description: guest
        in: header
        name: X-Username
        required: true
        type: string
      - default: EN
        description: EN
        in: header
        name: Accept-Language
        required: true
        type: string
      - description: BulkBookRequest
        in: body
        name: BookDto
        required: true
        schema:
          $ref: '#/definitions/shopping.BookBulkReq'
          type: object
      produces:
      - application/json
      responses:
        "200": {}
      summary: Shopping
      tags:
      - shopping-controller
  /shopping/book/find/{pubId}:
    get:
      consumes:
      - application/json
      description: Put all mandatory parameter
      parameters:
      - default: guest
        description: guest
        in: header
        name: X-Username
        required: true
        type: string
      - default: EN
        description: EN
        in: header
        name: Accept-Language
        required: true
        type: string
      - default: "1"
        description: publisherId
        in: path
        name: pubId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shopping.BookDto'
            type: object
      summary: Shopping
      tags:
      - shopping-controller
swagger: "2.0"
