// Code generated by ntaps. DO NOT EDIT.
package shared

import (
	"github.com/pkg/errors"
	"github.com/geb/aweproj/ses3/shared/config"
	"go.uber.org/dig"
)

func Register(container *dig.Container) error {
	if err := container.Provide(config.NewEnvConfiguration); err != nil {
		return errors.WithStack(err)
	}
	return nil
}
