// Code generated by ntaps. DO NOT EDIT.
package infrastructure

import (
	"github.com/pkg/errors"

	healthcheck_http "github.com/geb/aweproj/book-store/infrastructure/healthcheck"
	inventory_http "github.com/geb/aweproj/book-store/infrastructure/inventory"
	member_http "github.com/geb/aweproj/book-store/infrastructure/member"

	"go.uber.org/dig"
)

func Register(container *dig.Container) error {

	// - healthcheck-http-start
	if err := container.Provide(healthcheck_http.NewController); err != nil {
		return errors.Wrap(err, "failed to provide healthcheck controller")
	}
	// - healthcheck-http-end

	// - inventory-http-start
	if err := container.Provide(inventory_http.NewController); err != nil {
		return errors.Wrap(err, "failed to provide inventory controller")
	}
	// - inventory-http-end

	// - member-http-start
	if err := container.Provide(member_http.NewController); err != nil {
		return errors.Wrap(err, "failed to provide member controller")
	}
	// - member-http-end

	// - infrastructure-di-end
	return nil
}
