// Code generated by ntaps. DO NOT EDIT.
package infrastructure

import (
	"github.com/pkg/errors"


	healthcheck_http "github.com/geb/aweproj/ses3/infrastructure/healthcheck"

	"go.uber.org/dig"
)

func Register(container *dig.Container) error {

	// - healthcheck-http-start
	if err := container.Provide(healthcheck_http.NewController); err != nil {
		return errors.Wrap(err, "failed to provide healthcheck controller")
	}
	// - healthcheck-http-end


	// - infrastructure-di-end
	return nil
}
