// Code generated by ntaps. DO NOT EDIT.
package infrastructure

import (
	"github.com/geb/aweproj/ses3/shared"
	"log"

	"go.uber.org/dig"

	"fmt"

	_ "github.com/geb/aweproj/ses3/docs"
	healthcheck_http "github.com/geb/aweproj/ses3/infrastructure/healthcheck"
	inventory_http "github.com/geb/aweproj/ses3/infrastructure/inventory"
	member_http "github.com/geb/aweproj/ses3/infrastructure/member"
)

type (
	Holder struct {
		dig.In

		// - healthcheck-http-start
		HealthcheckController *healthcheck_http.Controller
		// - healthcheck-http-end

		// - inventory-http-start
		InventoryController *inventory_http.Controller
		// - inventory-http-end

		// - member-http-start
		MemberController *member_http.Controller
		// - member-http-end

		SharedHolder shared.Holder

		// - infrastructure-end
	}
)

func (h *Holder) ListenHttp() {

	// global middleware
	h.SharedHolder.Echo.Use(CustomMiddlewareLatency())

	ProtectedAPI(h)

	PublicAPI(h)

	if err := h.SharedHolder.Echo.Start(fmt.Sprintf(":%d", h.SharedHolder.Config.EchoServerPort)); err != nil {
		if err.Error() == "http: Server closed" {
			log.Printf("closing echo http server")
		} else {
			log.Printf("failed to start echo http server %s", err)
		}
	}

	// - http-end

}
